version: "3.8"

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-demo-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
